version: '3'
services:

  ui-vuejs:
    build: .
    volumes:
    ## Mount or copy (see Dockerfile)
    #- .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
